<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Dados dos municípios
        $municipios = [
            ['id' => 1, 'muninome' => 'Ambriz', 'provincia_id' => 1],
            ['id' => 2, 'muninome' => 'Bula Atumba', 'provincia_id' => 1],
            ['id' => 3, 'muninome' => 'Dande', 'provincia_id' => 1],
            ['id' => 4, 'muninome' => 'Dembos', 'provincia_id' => 1],
            ['id' => 5, 'muninome' => 'Nambuangongo', 'provincia_id' => 1],
            ['id' => 6, 'muninome' => 'Pango Aluquém', 'provincia_id' => 1],
            ['id' => 7, 'muninome' => 'Baia Farta', 'provincia_id' => 2],
            ['id' => 8, 'muninome' => 'Balombo', 'provincia_id' => 2],
            ['id' => 9, 'muninome' => 'Benguela', 'provincia_id' => 2],
            ['id' => 10, 'muninome' => 'Bocoio', 'provincia_id' => 2],
            ['id' => 11, 'muninome' => 'Caimbambo', 'provincia_id' => 2],
            ['id' => 12, 'muninome' => 'Catumbela', 'provincia_id' => 2],
            ['id' => 13, 'muninome' => 'Chongorói', 'provincia_id' => 2],
            ['id' => 14, 'muninome' => 'Cubal', 'provincia_id' => 2],
            ['id' => 15, 'muninome' => 'Ganda', 'provincia_id' => 2],
            ['id' => 16, 'muninome' => 'Lobito', 'provincia_id' => 2],
            ['id' => 17, 'muninome' => 'Andulo', 'provincia_id' => 3],
            ['id' => 18, 'muninome' => 'Camacupa', 'provincia_id' => 3],
            ['id' => 19, 'muninome' => 'Catabola', 'provincia_id' => 3],
            ['id' => 20, 'muninome' => 'Chinguar', 'provincia_id' => 3],
            ['id' => 21, 'muninome' => 'Chitembo', 'provincia_id' => 3],
            ['id' => 22, 'muninome' => 'Cuemba', 'provincia_id' => 3],
            ['id' => 23, 'muninome' => 'Cuito', 'provincia_id' => 3],
            ['id' => 24, 'muninome' => 'Cunhinga', 'provincia_id' => 3],
            ['id' => 25, 'muninome' => 'Nharêa', 'provincia_id' => 3],
            ['id' => 26, 'muninome' => 'Belize', 'provincia_id' => 4],
            ['id' => 27, 'muninome' => 'Buco Zau', 'provincia_id' => 4],
            ['id' => 28, 'muninome' => 'Cabinda', 'provincia_id' => 4],
            ['id' => 29, 'muninome' => 'Cacongo', 'provincia_id' => 4],
            ['id' => 30, 'muninome' => 'Calai', 'provincia_id' => 5],
            ['id' => 31, 'muninome' => 'Canguar', 'provincia_id' => 5],
            ['id' => 32, 'muninome' => 'Cuchi', 'provincia_id' => 5],
            ['id' => 33, 'muninome' => 'Cuito Cuanavale', 'provincia_id' => 5],
            ['id' => 34, 'muninome' => 'Dirico', 'provincia_id' => 5],
            ['id' => 35, 'muninome' => 'Mavinga', 'provincia_id' => 5],
            ['id' => 36, 'muninome' => 'Menongue', 'provincia_id' => 5],
            ['id' => 37, 'muninome' => 'Nancova', 'provincia_id' => 5],
            ['id' => 38, 'muninome' => 'Rivungo', 'provincia_id' => 5],
            ['id' => 39, 'muninome' => 'Ambaca', 'provincia_id' => 6],
            ['id' => 40, 'muninome' => 'Gulungo Alto', 'provincia_id' => 6],
            ['id' => 41, 'muninome' => 'Banga', 'provincia_id' => 6],
            ['id' => 42, 'muninome' => 'Bolongongo', 'provincia_id' => 6],
            ['id' => 43, 'muninome' => 'Cambambe', 'provincia_id' => 6],
            ['id' => 44, 'muninome' => 'Cazengo', 'provincia_id' => 6],
            ['id' => 45, 'muninome' => 'Lucala', 'provincia_id' => 6],
            ['id' => 46, 'muninome' => 'Ngonguembo', 'provincia_id' => 6],
            ['id' => 47, 'muninome' => 'Quiculungo', 'provincia_id' => 6],
            ['id' => 48, 'muninome' => 'Samba Cajú', 'provincia_id' => 6],
            ['id' => 49, 'muninome' => 'Conda', 'provincia_id' => 7],
            ['id' => 50, 'muninome' => 'Mussende', 'provincia_id' => 7],
            ['id' => 51, 'muninome' => 'Quilenda', 'provincia_id' => 7],
            ['id' => 52, 'muninome' => 'Amboim', 'provincia_id' => 7],
            ['id' => 53, 'muninome' => 'Cassongue', 'provincia_id' => 7],
            ['id' => 54, 'muninome' => 'Cela', 'provincia_id' => 7],
            ['id' => 55, 'muninome' => 'Ebo', 'provincia_id' => 7],
            ['id' => 56, 'muninome' => 'Libolo', 'provincia_id' => 7],
            ['id' => 57, 'muninome' => 'Porto Amboim', 'provincia_id' => 7],
            ['id' => 58, 'muninome' => 'Quibala', 'provincia_id' => 7],
            ['id' => 59, 'muninome' => 'Seles', 'provincia_id' => 7],
            ['id' => 60, 'muninome' => 'Sumbe', 'provincia_id' => 7],
            ['id' => 61, 'muninome' => 'Canhama', 'provincia_id' => 8],
            ['id' => 62, 'muninome' => 'Cuanhama', 'provincia_id' => 8],
            ['id' => 63, 'muninome' => 'Curoca', 'provincia_id' => 8],
            ['id' => 64, 'muninome' => 'Cuvelai', 'provincia_id' => 8],
            ['id' => 65, 'muninome' => 'Namacunde', 'provincia_id' => 8],
            ['id' => 66, 'muninome' => 'Ombandja', 'provincia_id' => 8],
            ['id' => 67, 'muninome' => 'Bailundo', 'provincia_id' => 9],
            ['id' => 68, 'muninome' => 'Caála', 'provincia_id' => 9],
            ['id' => 69, 'muninome' => 'Cachiungo', 'provincia_id' => 9],
            ['id' => 70, 'muninome' => 'Chicala-Cholohanga', 'provincia_id' => 9],
            ['id' => 71, 'muninome' => 'Chinjenje', 'provincia_id' => 9],
            ['id' => 72, 'muninome' => 'Ecunha', 'provincia_id' => 9],
            ['id' => 73, 'muninome' => 'Huambo', 'provincia_id' => 9],
            ['id' => 74, 'muninome' => 'Londuimbali', 'provincia_id' => 9],
            ['id' => 75, 'muninome' => 'Longonjo', 'provincia_id' => 9],
            ['id' => 76, 'muninome' => 'Mungo', 'provincia_id' => 9],
            ['id' => 77, 'muninome' => 'Ucuma', 'provincia_id' => 9],
            ['id' => 78, 'muninome' => 'Caconda', 'provincia_id' => 10],
            ['id' => 79, 'muninome' => 'Cacula', 'provincia_id' => 10],
            ['id' => 80, 'muninome' => 'Caluquembe', 'provincia_id' => 10],
            ['id' => 81, 'muninome' => 'Chibia', 'provincia_id' => 10],
            ['id' => 82, 'muninome' => 'Chicomba', 'provincia_id' => 10],
            ['id' => 83, 'muninome' => 'Chipindo', 'provincia_id' => 10],
            ['id' => 84, 'muninome' => 'Cuvango', 'provincia_id' => 10],
            ['id' => 85, 'muninome' => 'Gambos', 'provincia_id' => 10],
            ['id' => 86, 'muninome' => 'Humpata', 'provincia_id' => 10],
            ['id' => 87, 'muninome' => 'Jamba', 'provincia_id' => 10],
            ['id' => 88, 'muninome' => 'Lubango', 'provincia_id' => 10],
            ['id' => 89, 'muninome' => 'Matala', 'provincia_id' => 10],
            ['id' => 90, 'muninome' => 'Quilemgues', 'provincia_id' => 10],
            ['id' => 91, 'muninome' => 'Quipungo', 'provincia_id' => 10],
            ['id' => 92, 'muninome' => 'Belas', 'provincia_id' => 11],
            ['id' => 93, 'muninome' => 'Cacuaco', 'provincia_id' => 11],
            ['id' => 94, 'muninome' => 'Cazenga', 'provincia_id' => 11],
            ['id' => 95, 'muninome' => 'Icolo e Bengo', 'provincia_id' => 11],
            ['id' => 96, 'muninome' => 'Kilamba Kiaxi', 'provincia_id' => 11],
            ['id' => 97, 'muninome' => 'Luanda', 'provincia_id' => 11],
            ['id' => 98, 'muninome' => 'Quiçama', 'provincia_id' => 11],
            ['id' => 99, 'muninome' => 'Talatona', 'provincia_id' => 11],
            ['id' => 100, 'muninome' => 'Viana', 'provincia_id' => 11],
            ['id' => 101, 'muninome' => 'Capenda Camulenda', 'provincia_id' => 12],
            ['id' => 102, 'muninome' => 'Caungula', 'provincia_id' => 12],
            ['id' => 103, 'muninome' => 'Cuilo', 'provincia_id' => 12],
            ['id' => 104, 'muninome' => 'Lôvua', 'provincia_id' => 12],
            ['id' => 105, 'muninome' => 'Lubalo', 'provincia_id' => 12],
            ['id' => 106, 'muninome' => 'Xa-Muteba', 'provincia_id' => 12],
            ['id' => 107, 'muninome' => 'Chitato', 'provincia_id' => 12],
            ['id' => 108, 'muninome' => 'Cambulo', 'provincia_id' => 12],
            ['id' => 109, 'muninome' => 'Cuango', 'provincia_id' => 12],
            ['id' => 110, 'muninome' => 'Lucapa', 'provincia_id' => 12],
            ['id' => 111, 'muninome' => 'Caculo', 'provincia_id' => 13],
            ['id' => 112, 'muninome' => 'Dala', 'provincia_id' => 13],
            ['id' => 113, 'muninome' => 'Saurimo', 'provincia_id' => 13],
            ['id' => 114, 'muninome' => 'Muconda', 'provincia_id' => 13],
            ['id' => 115, 'muninome' => 'Cacuso', 'provincia_id' => 14],
            ['id' => 116, 'muninome' => 'Cahombo', 'provincia_id' => 14],
            ['id' => 117, 'muninome' => 'Calandula', 'provincia_id' => 14],
            ['id' => 118, 'muninome' => 'Cambundi Catembo', 'provincia_id' => 14],
            ['id' => 119, 'muninome' => 'Cangandala', 'provincia_id' => 14],
            ['id' => 120, 'muninome' => 'Kiwaba Nzoji', 'provincia_id' => 14],
            ['id' => 121, 'muninome' => 'Kunda Dya Baze', 'provincia_id' => 14],
            ['id' => 122, 'muninome' => 'Luquembo', 'provincia_id' => 14],
            ['id' => 123, 'muninome' => 'Malanje', 'provincia_id' => 14],
            ['id' => 124, 'muninome' => 'Marimba', 'provincia_id' => 14],
            ['id' => 125, 'muninome' => 'Massango', 'provincia_id' => 14],
            ['id' => 126, 'muninome' => 'Mucari', 'provincia_id' => 14],
            ['id' => 127, 'muninome' => 'Quela', 'provincia_id' => 14],
            ['id' => 128, 'muninome' => 'Quirima', 'provincia_id' => 14],
            ['id' => 129, 'muninome' => 'Alto Zambeze', 'provincia_id' => 15],
            ['id' => 130, 'muninome' => 'Bundas', 'provincia_id' => 15],
            ['id' => 131, 'muninome' => 'Camanongue', 'provincia_id' => 15],
            ['id' => 132, 'muninome' => 'Cameia', 'provincia_id' => 15],
            ['id' => 133, 'muninome' => 'Lubalo', 'provincia_id' => 12],
            ['id' => 134, 'muninome' => 'Lucapa', 'provincia_id' => 12],
            ['id' => 135, 'muninome' => 'Xá-Muteba', 'provincia_id' => 12],
            ['id' => 136, 'muninome' => 'Cacolo', 'provincia_id' => 12],
            ['id' => 137, 'muninome' => 'Capenda Camulemba', 'provincia_id' => 12],
            ['id' => 138, 'muninome' => 'Caungula', 'provincia_id' => 12],
            ['id' => 139, 'muninome' => 'Chitato', 'provincia_id' => 12],
            ['id' => 140, 'muninome' => 'Cuango', 'provincia_id' => 12],
            ['id' => 141, 'muninome' => 'Cuilo', 'provincia_id' => 12],
            ['id' => 142, 'muninome' => 'Lóvua', 'provincia_id' => 12],
            ['id' => 143, 'muninome' => 'Lubalo', 'provincia_id' => 12],
            ['id' => 144, 'muninome' => 'Lucapa', 'provincia_id' => 12],
            ['id' => 145, 'muninome' => 'Xá-Muteba', 'provincia_id' => 12],
            ['id' => 146, 'muninome' => 'Cacolo', 'provincia_id' => 12],
            ['id' => 147, 'muninome' => 'Capenda Camulemba', 'provincia_id' => 12],
            ['id' => 148, 'muninome' => 'Caungula', 'provincia_id' => 12],
            ['id' => 149, 'muninome' => 'Chitato', 'provincia_id' => 12],
            ['id' => 150, 'muninome' => 'Cuango', 'provincia_id' => 12],
            ['id' => 151, 'muninome' => 'Cuilo', 'provincia_id' => 12],
            ['id' => 152, 'muninome' => 'Lóvua', 'provincia_id' => 12],
            ['id' => 153, 'muninome' => 'Lubalo', 'provincia_id' => 12],
            ['id' => 154, 'muninome' => 'Lucapa', 'provincia_id' => 12],
            ['id' => 155, 'muninome' => 'Xá-Muteba', 'provincia_id' => 12],
            ['id' => 156, 'muninome' => 'Cacolo', 'provincia_id' => 12],
            ['id' => 157, 'muninome' => 'Capenda Camulemba', 'provincia_id' => 12],
            ['id' => 158, 'muninome' => 'Caungula', 'provincia_id' => 12],
            ['id' => 159, 'muninome' => 'Chitato', 'provincia_id' => 12],
            ['id' => 160, 'muninome' => 'Cuango', 'provincia_id' => 12],
            ['id' => 161, 'muninome' => 'Cuilo', 'provincia_id' => 12],
            ['id' => 162, 'muninome' => 'Lóvua', 'provincia_id' => 12],
            ['id' => 163, 'muninome' => 'Lubalo', 'provincia_id' => 12],
            ['id' => 164, 'muninome' => 'Tomboco', 'provincia_id' => 18],
        ];

        // Inserir os dados na tabela 'municipios'
        DB::table('municipios')->insert($municipios);
    }
}
